version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build .
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm ci && npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
